services:
  the-last-tradepost:
    build:
      context: .
    container_name: the-last-tradepost-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    container_name: the-last-tradepost-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5112:5432"
    volumes:
      - the-last-tradepost-postgresql:/data/db/postgresql

volumes:
  the-last-tradepost-postgresql:
    driver: local
