CREATE TABLE IF NOT EXISTS public."cart"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    session_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    item_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    price_at_time decimal(10,2) NOT NULL CHECK (price_at_time >= 0),
    added_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cart_pkey PRIMARY KEY (id),
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id)
        REFERENCES public."users" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_item FOREIGN KEY (item_id)
        REFERENCES public."items" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT unique_cart_item_session UNIQUE (session_token, item_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_cart_session_token ON public."cart" (session_token);
CREATE INDEX IF NOT EXISTS idx_cart_user_id ON public."cart" (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_id ON public."cart" (item_id);
CREATE INDEX IF NOT EXISTS idx_cart_added_at ON public."cart" (added_at);

-- Add comments
COMMENT ON TABLE public."cart" IS 'Shopping cart items for users, supports both session-based and user-based carts';
COMMENT ON COLUMN public."cart".session_token IS 'Session token for anonymous users or logged-in users session';
COMMENT ON COLUMN public."cart".user_id IS 'Optional: Links to user if logged in';
COMMENT ON COLUMN public."cart".price_at_time IS 'Price of item when added to cart (for price change tracking)';