CREATE TABLE IF NOT EXISTS public."items"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price decimal(10,2) NOT NULL CHECK (price >= 0),
    image_url text COLLATE pg_catalog."default",
    seller_id integer NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" DEFAULT 'general',
    stock_quantity integer NOT NULL DEFAULT 1 CHECK (stock_quantity >= 0),
    is_active boolean NOT NULL DEFAULT true,
    source character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'marketplace',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_items_seller FOREIGN KEY (seller_id)
        REFERENCES public."users" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_items_seller_id ON public."items" (seller_id);
CREATE INDEX IF NOT EXISTS idx_items_category ON public."items" (category);
CREATE INDEX IF NOT EXISTS idx_items_is_active ON public."items" (is_active);
CREATE INDEX IF NOT EXISTS idx_items_price ON public."items" (price);

-- Add comments
COMMENT ON TABLE public."items" IS 'Items available for purchase in the marketplace';
COMMENT ON COLUMN public."items".source IS 'Source of item: marketplace (user-uploaded) or shop (system items)';
COMMENT ON COLUMN public."items".seller_id IS 'References the user who listed the item';