CREATE TABLE IF NOT EXISTS public."receipts"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    receipt_number character varying(50) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    user_id integer,
    session_token character varying(255) COLLATE pg_catalog."default",
    total_amount decimal(10,2) NOT NULL CHECK (total_amount >= 0),
    tax_amount decimal(10,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    shipping_address text COLLATE pg_catalog."default" NOT NULL,
    billing_address text COLLATE pg_catalog."default",
    payment_method character varying(50) COLLATE pg_catalog."default" DEFAULT 'cash',
    payment_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'completed',
    order_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'processing',
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT receipts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_receipts_user FOREIGN KEY (user_id)
        REFERENCES public."users" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
    CONSTRAINT chk_order_status CHECK (order_status IN ('processing', 'shipped', 'delivered', 'cancelled'))
);

-- Receipt Items (Junction table for receipt items)
CREATE TABLE IF NOT EXISTS public."receipt_items"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    receipt_id integer NOT NULL,
    item_id integer NOT NULL,
    item_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    item_description text COLLATE pg_catalog."default",
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price decimal(10,2) NOT NULL CHECK (unit_price >= 0),
    total_price decimal(10,2) NOT NULL CHECK (total_price >= 0),
    seller_name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT receipt_items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_receipt_items_receipt FOREIGN KEY (receipt_id)
        REFERENCES public."receipts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_receipt_items_item FOREIGN KEY (item_id)
        REFERENCES public."items" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_receipts_user_id ON public."receipts" (user_id);
CREATE INDEX IF NOT EXISTS idx_receipts_session_token ON public."receipts" (session_token);
CREATE INDEX IF NOT EXISTS idx_receipts_receipt_number ON public."receipts" (receipt_number);
CREATE INDEX IF NOT EXISTS idx_receipts_created_at ON public."receipts" (created_at);
CREATE INDEX IF NOT EXISTS idx_receipts_payment_status ON public."receipts" (payment_status);
CREATE INDEX IF NOT EXISTS idx_receipts_order_status ON public."receipts" (order_status);

CREATE INDEX IF NOT EXISTS idx_receipt_items_receipt_id ON public."receipt_items" (receipt_id);
CREATE INDEX IF NOT EXISTS idx_receipt_items_item_id ON public."receipt_items" (item_id);

-- Add comments
COMMENT ON TABLE public."receipts" IS 'Purchase receipts with generated delivery addresses';
COMMENT ON COLUMN public."receipts".receipt_number IS 'Unique receipt identifier (format: RCP-YYYYMMDD-XXXX)';
COMMENT ON COLUMN public."receipts".shipping_address IS 'Randomly generated delivery address';
COMMENT ON COLUMN public."receipts".session_token IS 'Session token for guest purchases';

COMMENT ON TABLE public."receipt_items" IS 'Individual items within a receipt';
COMMENT ON COLUMN public."receipt_items".item_name IS 'Snapshot of item name at time of purchase';
COMMENT ON COLUMN public."receipt_items".unit_price IS 'Price per unit at time of purchase';
COMMENT ON COLUMN public."receipt_items".total_price IS 'Total price for this line item (quantity * unit_price)';