CREATE TABLE IF NOT EXISTS public."users"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default" NOT NULL,
    gender character varying(20) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'user',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_email_key UNIQUE (email),
    CONSTRAINT user_username_key UNIQUE (username),
    CONSTRAINT chk_gender CHECK (gender IN ('male', 'female', 'others')),
    CONSTRAINT chk_role CHECK (role IN ('user', 'admin'))
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_username ON public."users" (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON public."users" (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public."users" (role);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public."users" (created_at);

-- Add comments
COMMENT ON TABLE public."users" IS 'User accounts for the trading platform';
COMMENT ON COLUMN public."users".username IS 'Unique username/codename for login';
COMMENT ON COLUMN public."users".email IS 'User email address (optional)';
COMMENT ON COLUMN public."users".gender IS 'User gender selection';
COMMENT ON COLUMN public."users".role IS 'User role: user or admin';
